### ISSUE TITLE
History plugin will be initialized before TShock

### ISSUE THREAD

**Issue by mistzzt** [MarioE/History#11]
However, the plugin works well. 
But I don't know if it should act like this.

**Comment by cracker64** [comment]
Is this really an issue?
I changed this because History has been double checking region and user permissions, this should be TShock's job and we can just use that result.
Only ServerAPI hooks are initialized before TShock, and this actually causes GetData to run after TShock processes it.

The only change that is possible is changing back the plugin order, and using the Hook priority when registering GetData.  This doesn't change any behavior besides where 'History' shows up on the boot screen.

**Comment by mistzzt** [comment]
ok, i got it.
thx for all your hard work
